### ISSUE TITLE
basics: introduce add_hazard etc vormittags  

### ISSUE THREAD

**Issue by fabian-s** [adibender/iwsm-2023-shortcourse#2]

**Comment by fabian-s** [comment]
use tumor example at the end of pem.Rmd

**Comment by adibender** [comment]
also: how to "elegantly" calculate "complex" HR with `make_newdata(..., refernce= list(...)) |> add_hazard()` 
probably also need to explain (X1 - X2) * beta formally

**Comment by fabian-s** [comment]
seems  covered by [fe66d4](https://github.com/adibender/iwsm-2023-shortcourse/commit/fe66d4296ba6c36a3b9d1fa8946029ae952a9cb0), mostly?
